#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.CycleTimer
methods = (
    'new',
    'get_timestamp',
    'get_clock_id',
    'get_cycle_timer',
)

if not test_struct(target, methods):
    exit(ENXIO)
