#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.FwIsoTx()
props = ()
methods = (
    'new',
    'allocate',
    'release',
    'map_buffer',
    'unmap_buffer',
    'start',
    'stop',
    'register_packet',
)
vmethods = (
    'do_interrupted',
)
signals = (
    'interrupted',
)

if not test_object(target, props, methods, vmethods, signals):
    exit(ENXIO)
