#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.FwIsoRxMultiple()
props = ()
methods = (
    'new',
    'allocate',
    'release',
    'map_buffer',
    'unmap_buffer',
    'start',
    'stop',
)
vmethods = ()
signals = (
    'interrupted',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
