#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target_type = Hinoko.FwIsoResource
props = (
    'generation',
)
methods = (
    'open',
    'create_source',
    'allocate',
    'allocate_wait',
)
vmethods = (
    'do_open',
    'do_allocate',
    'do_create_source',
    'do_allocated',
    'do_deallocated',
)
signals = (
    'allocated',
    'deallocated',
)

if not test_object(target_type,  props, methods, vmethods, signals):
    exit(ENXIO)
