#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.FwIsoResource()
props = ()
methods = (
    'new',
    'open',
    'create_source',
    'calculate_bandwidth',
    'allocate_once_async',
    'deallocate_once_async',
)
vmethods = (
    'do_allocated',
    'do_deallocated',
)
signals = (
    'allocated',
    'deallocated',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)

