#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target_type = Hinoko.FwIsoIrMultiple
props = (
    'channels',
    # From interface.
    'bytes-per-chunk',
    'chunks-per-buffer',
)
methods = (
    'new',
    'allocate',
    'map_buffer',
    'start',
    'get_payload',
    # From interface.
    'stop',
    'unmap_buffer',
    'release',
    'get_cycle_timer',
    'create_source',
    'flush_completions',
)
vmethods = (
    'do_interrupted',
    # From interface.
    'do_stop',
    'do_unmap_buffer',
    'do_release',
    'do_get_cycle_timer',
    'do_flush_completions',
    'do_create_source',
    'do_stopped',
)
signals = (
    'interrupted',
    # From interface.
    'stopped',
)

if not test_object(target_type,  props, methods, vmethods, signals):
    exit(ENXIO)
