#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.FwIsoCtx
props = (
    'bytes-per-chunk',
    'chunks-per-buffer',
    'registered-chunk-count',
)
methods = (
    'get_cycle_timer',
    'create_source',
)
vmethods = ()
signals = (
    'stopped',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
