#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target_type = Hinoko.FwIsoResourceAuto
props = (
    'is-allocated',
    'channel',
    'bandwidth',
    # From interface.
    'generation',
)
methods = (
    'new',
    'deallocate',
    'deallocate_wait',
    # From interface.
    'open',
    'create_source',
    'allocate_async',
    'allocate_sync',
)
vmethods = (
    # From interface.
    'do_open',
    'do_allocate_async',
    'do_create_source',
    'do_allocated',
    'do_deallocated',
)
signals = (
    # From interface.
    'allocated',
    'deallocated',
)

if not test_object(target_type,  props, methods, vmethods, signals):
    exit(ENXIO)

