#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '1.0')
from gi.repository import Hinoko

target_type = Hinoko.FwIsoCtx
props = (
    'bytes-per-chunk',
    'chunks-per-buffer',
)
methods = (
    'stop',
    'unmap_buffer',
    'release',
    'read_cycle_time',
    'create_source',
    'flush_completions',
)
vmethods = (
    'do_stop',
    'do_unmap_buffer',
    'do_release',
    'do_read_cycle_time',
    'do_flush_completions',
    'do_create_source',
    'do_stopped',
)
signals = (
    'stopped',
)

if not test_object(target_type,  props, methods, vmethods, signals):
    exit(ENXIO)
