#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target = Hinoko.FwIsoResourceAuto()
props = (
    'allocated',
    'channel',
    'bandwidth',
)
methods = (
    'new',
    'allocate_async',
)
vmethods = ()
signals = ()

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)

