#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

target_type = Hinoko.FwIsoRxMultiple
props = (
    'channels',
)
methods = (
    'new',
    'allocate',
    'release',
    'map_buffer',
    'unmap_buffer',
    'start',
    'stop',
    'get_payload',
)
vmethods = (
    'do_interrupted',
)
signals = (
    'interrupted',
)

if not test_object(target_type,  props, methods, vmethods, signals):
    exit(ENXIO)
