#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('Hinoko', '0.0')
from gi.repository import Hinoko

from helper import test_functions

types = {
    Hinoko.FwIsoResource: (
        'calculate_bandwidth',
    ),
    Hinoko.FwIsoCtxError: (
        'quark',
    ),
    Hinoko.FwIsoResourceError: (
        'quark',
    ),
    Hinoko.FwIsoResourceAutoError: (
        'quark',
    ),
}

for target_type, functions in types.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
